### ISSUE TITLE
'GameClient: unknown event' while sending message to controller

### ISSUE THREAD

**Issue by Kovah** [greggman/HappyFunTimes#23]
I followed the docs on sending messages from the game to the phones and implemented the following code:

**game.js**
```javascript
player.netPlayer.sendCmd('roundStart', data)
```

**controller.js**
```javascript
function onRoundStart() {
    //
}

var g_client = new GameClient();
g_client.addEventListener('roundStart', onRoundStart());
```

However, I get the following error in the console after the message arrived on the phone:
`GameClient: unknown event: roundStart`

Am I doing something wrong? I already tried other spellings like `round-start` and `roundstart` but none worked. Do I have to add custom events anywhere?

**Comment by greggman** [comment]
I think maybe you want

    g_client.addEventListener('roundStart', onRoundStart);

Not

    g_client.addEventListener('roundStart', onRoundStart());

**Comment by Kovah** [comment]
Thanks! This solved the problem!
