### ISSUE TITLE
Download / Install links for linux do not work

### ISSUE THREAD

**Issue by MikeDX** [greggman/HappyFunTimes#26]
The link:

https://github.com/greggman/HappyFunTimes/blob/master/docs/linux.md

does not work from the page:

http://superhappyfuntimes.net/install

I'm sure this used to work. Is there an alternative?

**Comment by PixelRetro** [comment]
The location of the file seems to have changed. You can find it [here](https://github.com/greggman/HappyFunTimes/blob/master/docs/setup/linux.md).

**Comment by MikeDX** [comment]
Thanks for the link, but I'm more reporting it so the link can be updated on the superhappyfuntimes.net page really.

**Comment by greggman** [comment]
Sorry, they were moved a few days ago in #25 

I added some redirects. The page you're looking for is now here

https://github.com/greggman/HappyFunTimes/blob/master/docs/setup/linux.md
