### ISSUE TITLE
Custom URL

### ISSUE THREAD

**Issue by teacoat** [greggman/HappyFunTimes#27]
I was wondering if it was possible to recreate the functionality of your HappyFunTimes Redirector? I basically want to keep that branded in line with the game. 

Is there any info you could give on this?

**Comment by greggman** [comment]
Yes, the happyfuntimes.net server is here

http://github.com/greggman/happyfuntimes.net

1. Setup your own server ($5 a month on digital ocean for example) 
2.point some domain at it
3. In your `PlayerSpawner` or `PlayerConnector` set `Rendezvous Url` to `http://yourdomain.com/api/inform2`
4. Tell your players to go to `yourdomain.com`

I'll see if I can post some deployment scripts

**Comment by teacoat** [comment]
Awesome thanks!

**Comment by teacoat** [comment]
One more thing, what would be the most reliable way to run this without internet access?

**Comment by greggman** [comment]
To run the game without internet access see 

http://docs.happyfuntimes.net/docs/network.html
