### ISSUE TITLE
Left,Right,Top,Bottom buttons don't work in IOS Safari

### ISSUE THREAD

**Issue by immiao** [greggman/HappyFunTimes#28]
But the other buttons work well. What could be the possible reason?

**Comment by greggman** [comment]
I think I need more info. 

I just tried it with iOS 10.3.2 and it worked for me.

Do you have an ad blocker installed?

**Comment by immiao** [comment]
Oh. It's caused by disallowing cookies. It works well after I enable cookies. Thanks a lot!

**Comment by greggman** [comment]
thank you for telling me what it was. I will try to fix it so it works even if cookies are disabled
