### ISSUE TITLE
Run hft without electron

### ISSUE THREAD

**Issue by nantas** [greggman/HappyFunTimes#29]
Hi there, I'm wondering how to run hft game without electron? I'm using cocos as client game engine but got this error:

```js
:7456/build/src/project.js:1 WebSocket connection to 'ws://localhost:7456/' failed: Connection closed before receiving a handshake response
```

I'd like to know how to start websocket server if not using electron but a hosted web page?

**Comment by greggman** [comment]
What do you mean by hosted webpage? If you're running without electron then happyfuntimes would serve the page for you. There'd be no reason to serve it from somewhere else.

Here's an example

https://github.com/greggman/hft-simple-no-electron

**Comment by nantas** [comment]
Cool, that's exactly what I'm looking for. Thanks a lot!
