### ISSUE TITLE
Inform Co-routine failing in Unity 2017

### ISSUE THREAD

**Issue by DunkUK** [greggman/HappyFunTimes#33]
HappyFunTimes informs happyfuntimes.net of a running server in Informer.InformCoroutine() by sending a www message with custom headers.  In Unity 2017, trying to manually set a "Host" header will throw an exception: (InvalidOperationException: Cannot override system-specified headers).

Removing the host header will cause the exception to go away, but then the game never registers itself because the server is returning error 503 (probably because the host header is expected server-side).

Since the host header isn't getting set automatically client-side due to usage of a direct ip address, I added an Informer object that just used the happyfuntimes.net hostname, without converting that to a IPv4 or v6 address.  This sets the host-header correctly, and so registers the game correctly and everything is happy and fun again.

Probably this might warrant a proper fix though, since I assume the direct IP conversion was done for a reason...

**Comment by greggman** [comment]
Thank you for the ideas on how to fix it.

Yes, IIRC the direct IP lookup is to handle IPv6 because unity was failing to ever use the IPv6 address for a domain.

**Comment by greggman** [comment]
Ok I uploaded a new version

The only changes are in [HTFSite.cs](https://github.com/greggman/hft-unity3d/blob/master/Assets/HappyFunTimes/HappyFunTimesCore/Server/HFTSite.cs)

**Comment by greggman** [comment]
Here's the unity package

https://github.com/greggman/hft-unity3d/releases/tag/v2.1.3
