### ISSUE TITLE
Unity 2019.2.3f1 Broken

### ISSUE THREAD

**Issue by srgers10** [greggman/HappyFunTimes#34]
Hi, I've been working on a project and updated unity to the newest release and now HappyFunTimes doesn't work. It returns the following error. Any suggestions on how to fix it?

UriFormatException: Invalid URI: Invalid port specified.
UnityEngineInternal.WebRequestUtils.MakeInitialUrl (System.String targetUrl, System.String localUrl) (at C:/buildslave/unity/build/Modules/UnityWebRequest/Public/WebRequestUtils.cs:540)
UnityEngine.Networking.UnityWebRequest.set_url (System.String value) (at C:/buildslave/unity/build/Modules/UnityWebRequest/Public/UnityWebRequest.bindings.cs:400)
UnityEngine.Networking.UnityWebRequest..ctor (System.String url, System.String method) (at C:/buildslave/unity/build/Modules/UnityWebRequest/Public/UnityWebRequest.bindings.cs:176)
HappyFunTimes.HFTSite+Informer+<InformCoroutine>d__15.MoveNext () (at Assets/HappyFunTimes/HappyFunTimesCore/Server/HFTSite.cs:89)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
HappyFunTimes.Informer:Inform(Boolean, MonoBehaviour, Byte[], String) (at Assets/HappyFunTimes/HappyFunTimesCore/Server/HFTSite.cs:72)
HappyFunTimes.<CheckAddresses>d__8:MoveNext() (at Assets/HappyFunTimes/HappyFunTimesCore/Server/HFTSite.cs:240)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by greggman** [comment]
Have you tried the one here from github?

https://github.com/greggman/hft-unity3d/releases

**Comment by srgers10** [comment]
That seemed to work. Thanks!
