### ISSUE TITLE
Looking for executable with wrong name on Linux (Unity3D)

### ISSUE THREAD

**Issue by PixelRetro** [greggman/HappyFunTimes#8]
When I download and want to play a HFT Unity game on Linux, then HFT wants to start "[name]-linux", instead of "[name]-linux.x86", saying "native game does not exist".
Also the executable flag must be set, otherwise the game cannot be started.

A workaround is renaming the executable and setting the executable flag manually, obviously.

![hfterror](https://cloud.githubusercontent.com/assets/5948405/7391092/6178d3ea-ee7e-11e4-85f1-03cd5f6aa46b.png)

**Comment by greggman** [comment]
Thanks! I pushed a fix I think in top of tree on master. you'll have to rename your file back the way it was but stuff *should* work after that.

**Comment by PixelRetro** [comment]
Great, everything is working :smile:
